/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uts_pbo_07_dhea;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dhea
 */
public class FrameMain extends javax.swing.JFrame {
    
    String nol_jam="";
    String nol_menit="";
    String nol_detik="";

    /**
     * Creates new form FrameMain
     */
    public FrameMain() {
        initComponents();
        setTanggal();
        setJam();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        lbltanggal = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtHarga = new javax.swing.JTextField();
        cbTujuan = new javax.swing.JComboBox<>();
        cbAwal = new javax.swing.JComboBox<>();
        txttanggal = new com.toedter.calendar.JDateChooser();
        rdEksekutif = new javax.swing.JRadioButton();
        rdEkonomi = new javax.swing.JRadioButton();
        cbDuduk = new javax.swing.JComboBox<>();
        cbWaktu = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        btnPrint = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblData = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblJam = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 153, 153));
        jPanel2.setLayout(null);

        lbltanggal.setBackground(new java.awt.Color(255, 255, 255));
        lbltanggal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel2.add(lbltanggal);
        lbltanggal.setBounds(700, 50, 100, 30);

        jPanel4.setBackground(new java.awt.Color(255, 204, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "ISI DATA TIKET", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanel4.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Nama Pemesan");
        jPanel4.add(jLabel1);
        jLabel1.setBounds(20, 30, 110, 30);
        jPanel4.add(txtNama);
        txtNama.setBounds(130, 30, 170, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("No ID");
        jPanel4.add(jLabel2);
        jLabel2.setBounds(20, 70, 80, 30);
        jPanel4.add(txtId);
        txtId.setBounds(130, 70, 170, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Station Awal");
        jPanel4.add(jLabel3);
        jLabel3.setBounds(20, 110, 80, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Station Tujuan");
        jPanel4.add(jLabel4);
        jLabel4.setBounds(20, 150, 110, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Tanggal Berangkat");
        jPanel4.add(jLabel5);
        jLabel5.setBounds(320, 30, 110, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Jenis Kereta");
        jPanel4.add(jLabel6);
        jLabel6.setBounds(320, 70, 80, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Waktu Berangkat");
        jPanel4.add(jLabel7);
        jLabel7.setBounds(320, 110, 100, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Tempat Duduk");
        jPanel4.add(jLabel8);
        jLabel8.setBounds(320, 150, 110, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Harga");
        jPanel4.add(jLabel9);
        jLabel9.setBounds(630, 30, 80, 30);
        jPanel4.add(txtHarga);
        txtHarga.setBounds(690, 30, 170, 30);

        cbTujuan.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbTujuan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Pilih Stasiun --", "Stasiun Malang", "Stasiun Surabaya", "Stasiun Blitar", "Stasiun Tulungagung", "Stasiun Sidoarjo" }));
        jPanel4.add(cbTujuan);
        cbTujuan.setBounds(130, 150, 170, 30);

        cbAwal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbAwal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Pilih Stasiun --", "Stasiun Malang", "Stasiun Surabaya", "Stasiun Blitar", "Stasiun Tulungagung", "Stasiun Sidoarjo" }));
        jPanel4.add(cbAwal);
        cbAwal.setBounds(130, 110, 170, 30);
        jPanel4.add(txttanggal);
        txttanggal.setBounds(440, 30, 170, 30);

        buttonGroup1.add(rdEksekutif);
        rdEksekutif.setText("Eksekutif");
        jPanel4.add(rdEksekutif);
        rdEksekutif.setBounds(440, 70, 90, 30);

        buttonGroup1.add(rdEkonomi);
        rdEkonomi.setText("Ekonomi");
        jPanel4.add(rdEkonomi);
        rdEkonomi.setBounds(530, 70, 80, 30);

        cbDuduk.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbDuduk.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Pilih Gerbong --", "Gerbong 1", "Gerbong 2", "Gerbong 3", "Gerbong 4", "Gerbong 5" }));
        cbDuduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDudukActionPerformed(evt);
            }
        });
        jPanel4.add(cbDuduk);
        cbDuduk.setBounds(440, 150, 170, 30);

        cbWaktu.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbWaktu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Pilih Waktu Berangkat --", "05.00", "07.00", "10.00", "14.30", "17.00", "19.00", "20.30" }));
        cbWaktu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbWaktuActionPerformed(evt);
            }
        });
        jPanel4.add(cbWaktu);
        cbWaktu.setBounds(440, 110, 170, 30);

        jPanel3.setBackground(new java.awt.Color(255, 153, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(null);

        btnPrint.setBackground(new java.awt.Color(255, 204, 204));
        btnPrint.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnPrint.setText("Print");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });
        jPanel3.add(btnPrint);
        btnPrint.setBounds(70, 70, 80, 30);

        btnDelete.setBackground(new java.awt.Color(255, 204, 204));
        btnDelete.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel3.add(btnDelete);
        btnDelete.setBounds(130, 40, 80, 30);

        btnSave.setBackground(new java.awt.Color(255, 204, 204));
        btnSave.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel3.add(btnSave);
        btnSave.setBounds(10, 10, 80, 30);

        btnClear.setBackground(new java.awt.Color(255, 204, 204));
        btnClear.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        jPanel3.add(btnClear);
        btnClear.setBounds(130, 10, 80, 30);

        btnRefresh.setBackground(new java.awt.Color(255, 204, 204));
        btnRefresh.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        jPanel3.add(btnRefresh);
        btnRefresh.setBounds(10, 40, 80, 30);

        jPanel4.add(jPanel3);
        jPanel3.setBounds(630, 70, 230, 110);

        jPanel2.add(jPanel4);
        jPanel4.setBounds(10, 140, 880, 210);

        jPanel5.setBackground(new java.awt.Color(255, 204, 204));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanel5.setLayout(null);

        tblData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "NamaPemesan", "NoID", "StationAwal", "StationTujuan", "TanggalBerangkat", "Jenis", "WaktuBerangkat", "TempatDuduk", "Harga"
            }
        ));
        jScrollPane1.setViewportView(tblData);

        jPanel5.add(jScrollPane1);
        jScrollPane1.setBounds(10, 10, 860, 150);

        jPanel2.add(jPanel5);
        jPanel5.setBounds(10, 360, 880, 170);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel10.setIcon(new javax.swing.ImageIcon("D:\\DATA 1\\MOKLET\\XI RPL 3\\SEMESTER 2\\PEMROGRAMAN BERBASIS OBJEK\\UTS_PBO_07_DHEA\\logo - Copy.png")); // NOI18N
        jPanel1.add(jLabel10);

        jPanel6.add(jPanel1);
        jPanel1.setBounds(0, 0, 170, 120);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel11.setText("PEMESANAN TIKET KERETA API");
        jPanel6.add(jLabel11);
        jLabel11.setBounds(200, 30, 380, 60);

        lblJam.setBackground(new java.awt.Color(255, 255, 255));
        lblJam.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel6.add(lblJam);
        lblJam.setBounds(690, 70, 120, 30);

        jPanel2.add(jPanel6);
        jPanel6.setBounds(10, 10, 880, 120);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 900, 540);

        setSize(new java.awt.Dimension(917, 581));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cbDudukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbDudukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbDudukActionPerformed

    private void cbWaktuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbWaktuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbWaktuActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String tanggal = dateFormat.format(txttanggal.getDate());
        
        if ("".equals(txtNama.getText()) || "".equals(txtId.getText()) ||
                "".equals(cbAwal.getSelectedItem()) || "".equals(cbTujuan.getSelectedItem()) || tanggal.equals("") 
                || "".equals(cbWaktu.getSelectedItem()) || "".equals(cbDuduk.getSelectedItem()) || "".equals(txtHarga.getText()))
        {
            JOptionPane.showMessageDialog(this, "Harap Lengkapi Data","Error", JOptionPane.WARNING_MESSAGE);
        }
        else
        {
            String JK = "";
                if (rdEksekutif.isSelected())
                {
                    JK = "Eksekutif";
                }else
                {
                    JK = "Ekonomi";
                }
            String SQL = "INSERT tb_pemesan (NamaPemesan,NoID,StationAwal,StationTujuan,TanggalBerangkat,JenisKereta,WaktuBerangkat,TempatDuduk,Harga)"
                    + "VALUES('"+txtNama.getText()+"','"+txtId.getText()+"','"+cbAwal.getSelectedItem()+"','"+cbTujuan.getSelectedItem()+"','"+tanggal+"','"+JK+"',"
                    + "'"+cbWaktu.getSelectedItem()+"','"+cbDuduk.getSelectedItem()+"','"+txtHarga.getText()+"')";
            int status = KoneksiDB.execute(SQL);
            if (status == 1){
                JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            }else
            {
                JOptionPane.showMessageDialog(this, "Data gagal ditambahkan", "Sukses", JOptionPane.WARNING_MESSAGE);
            }
            
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        txtId.setText("");
        txtNama.setText("");
        cbAwal.setSelectedIndex(0);
        cbTujuan.setSelectedIndex(0);
        txttanggal.setCalendar(null);
        buttonGroup1.clearSelection();
        cbWaktu.setSelectedIndex(0);
        cbDuduk.setSelectedIndex(0);
        txtHarga.setText("");
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        selectData();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int baris = tblData.getSelectedRow();
        if (baris != -1){
            String id = tblData.getValueAt(baris, 1).toString();
            String SQL = "DELETE FROM tb_pemesan WHERE NoID = '"+id+"'";
            int status = KoneksiDB.execute(SQL);
            if (status == 1){
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(this, "Data gagal dihapus", "Gagal", JOptionPane.WARNING_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(this, "Pilih Baris Data Terlebih Dahulu", "Error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        // TODO add your handling code here:
        /*MessageFormat header = new MessageFormat("Data Calon Penumpang Kereta Api");
        MessageFormat footer = new MessageFormat("Page {0,number,integer}   ");
        try{
            tblData.print(JTable.PrintMode.FIT_WIDTH, header, footer, true, null, true, null);
        }
        catch (java.awt.print.PrinterException e){
            System.err.format("Cannot print %s%n", e.getMessage());
        }*/
        JOptionPane.showMessageDialog(this, "Data anda akan di proses","Sukses", JOptionPane.INFORMATION_MESSAGE);
        dispose();
    }//GEN-LAST:event_btnPrintActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSave;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbAwal;
    private javax.swing.JComboBox<String> cbDuduk;
    private javax.swing.JComboBox<String> cbTujuan;
    private javax.swing.JComboBox<String> cbWaktu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblJam;
    private javax.swing.JLabel lbltanggal;
    private javax.swing.JRadioButton rdEkonomi;
    private javax.swing.JRadioButton rdEksekutif;
    private javax.swing.JTable tblData;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNama;
    private com.toedter.calendar.JDateChooser txttanggal;
    // End of variables declaration//GEN-END:variables

    private void selectData() {
        //To change body of generated methods, choose Tools | Templates.
        String kolom[] = {"NamaPemesan","NoID","StationAwal","StationTujuan","TanggalBerangkat","JenisKereta","WaktuBerangkat","TempatDuduk","Harga"};
        DefaultTableModel dtm = new DefaultTableModel(null, kolom);
        String SQL = "SELECT * FROM tb_pemesan";
        ResultSet rs = KoneksiDB.executeQuery(SQL);
        try{
            while(rs.next()){
                String NamaPemesan = rs.getString(1);
                String NoID = rs.getString(2);
                String StationAwal = rs.getString(3);
                String StationTujuan = rs.getString(4);
                
                SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
                String TanggalBerangkat = dateFormat.format(txttanggal.getDate());
                TanggalBerangkat = rs.getString(5);
                
                String JenisKereta = "";
                if ("Eksekutif".equals(rs.getString(6))){
                    JenisKereta = "Eksekutif";
                }else {
                    JenisKereta = "Ekonomi";
                }
                String WaktuBerangkat = rs.getString(7);
                String TempatDuduk = rs.getString(8);
                String Harga = rs.getString(9);
                String data[] = {NamaPemesan,NoID,StationAwal,StationTujuan,TanggalBerangkat,JenisKereta,WaktuBerangkat,TempatDuduk,Harga};
                dtm.addRow(data);
            }
        }
        catch(SQLException ex){
            Logger.getLogger(FrameMain.class.getName()).log(Level.SEVERE, null, ex);
        }
        tblData.setModel(dtm);     
    }
    
    public void setTanggal(){
        java.util.Date skrg = new java.util.Date();
        java.text.SimpleDateFormat kal = new java.text.SimpleDateFormat("dd/MM/yyyy");
        lbltanggal.setText(kal.format(skrg));
    }
    
    public void setJam(){
        ActionListener taskPerformer = new ActionListener() {
            
            public void actionPerformed(ActionEvent evt) {
                Date dt = new Date();
                int nilai_jam = dt.getHours();
                int nilai_menit = dt.getMinutes();
                int nilai_detik = dt.getSeconds();
                
                if(nilai_jam<= 9){
                    nol_jam = "0";
                }
                if(nilai_menit <= 9){
                    nol_menit = "0";
                }
                if(nilai_detik <= 9){
                    nol_detik = "0";
                }
                
                String jam = nol_jam + Integer.toString(nilai_jam);
                String menit = nol_menit + Integer.toString(nilai_menit);
                String detik = nol_detik + Integer.toString(nilai_detik);
                lblJam.setText("Jam : "+ jam + ":" + menit + ":" + detik);
            }
        };
        new Timer(100, taskPerformer).start();
    }
}
